### ISSUE TITLE
Cannot avoid brush selection reset 

### ISSUE THREAD

**Issue by AlainRo** [d3/d3-brush#22]
A click in the extent outside the selection rectangle reset the 2D brush selection to null. Fair enough.
But is it possible to take control of this behavior which occurs before the brush start event ??

This issue can be seen in this example:
http://bl.ocks.org/AlainRo/9264cd08e341f2c92f020c39642c34d1

**Comment by mbostock** [comment]
As I like to say, everything is possible, it’s just a question of how much work is involved. You have a few options:

* Remove the overlay element from the brush after applying it.

```js
svg.append("g")
    .attr("class", "brush")
    .call(d3.brush().on("brush", brushed))
  .selectAll(".overlay")
    .remove();
```

* Register a listener that takes priority for input events that would initiate a brush gesture, namely *mousedown* or *touchstart*. See https://github.com/d3/d3-zoom/issues/66#issuecomment-255175895 for a related discussion of event propagation; probably the easiest thing is to use a capturing event listener and then call *event*.stopImmediatePropagation (or *event*.stopPropagation) to prevent the brush from receiving the initiating input event.

* Use [*brush*.filter](https://github.com/d3/d3-brush/blob/master/README.md#brush_filter) to tell the brush to ignore input events on the overlay (using *event*.target to detect the receiving element; see [brush.js](https://github.com/d3/d3-brush/blob/master/src/brush.js#L296)), so that they won’t start a brush gesture.

* Use a *start* [brush event listener](https://github.com/d3/d3-brush/blob/master/README.md#brush-events) to set the brush selection to something other than null as desired. See [Brush Snapping II](https://bl.ocks.org/mbostock/6232620) for an example, although note that this doesn’t snap the brush on *start* (because it intentionally preserves the normal brush behavior of letting you clear the brush selection by clicking on the background).

If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
