### ISSUE TITLE
Calling `brush.move` does not update the internal state's selection

### ISSUE THREAD

**Issue by SylvainCorlay** [d3/d3-brush#42]
When e.g. resizing a figure, we call `brush.move` on active brush selectors to adjust to the resized figure.

The internal state of the brush is not updated by the call to `move` causing the interval to jump upon drag.

Our current workaround is to make another call to `brush()` to update the internal state.

**Comment by mbostock** [comment]
I’m not able to reproduce this problem. Here is a working example of brush.move (using transitions, but it works with or without it).

https://observablehq.com/d/a156d984f85884b2

When reporting an issue, please include a link to a live example, preferably as an [Observable notebook](https://beta.observablehq.com) or as a pull request in the [appropriate repository](https://github.com/d3) with tests. You should demonstrate that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md) using the minimum amount of code.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and define precisely how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? By isolating the issue, you assist the investigation.

Non-actionable bugs may be closed until you provide additional information. If you can’t isolate the bug further, please reply and ask for help. However, please be patient: open-source maintainers have many competing responsibilities—fixing other bugs, answering questions, developing features, writing documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by SylvainCorlay** [comment]
Sorry for the inacurate bug description. Now posting a more accurante description of the issue.
