### ISSUE TITLE
brush.on("end", handle) seems to get raw "mouseup" events

### ISSUE THREAD

**Issue by gnarf** [d3/d3-brush#9]
http://jsbin.com/rofenucicu/2/edit?js,console,output

I was expecting this to return an "end" event with a `event.selection`

**Comment by mbostock** [comment]
This is probably an issue with your use of destructuring assignment rather than import:

```js
const {brush, event, select} = d3;
```

The problem with this is that d3.event is not a constant: it changes whenever there’s an event.

So you should expect `event` to always be undefined in your example. But it’s not because some browsers emulate IE’s global [*window*.event](https://developer.mozilla.org/en-US/docs/Web/API/Window/event), overriding your `const event`, and hence you are seeing the native input events rather than the brush events.

If you change your code to refer to `d3.event` instead of `event`, and remove the destructuring assignment, it works fine. If you use vanilla JavaScript, it also works fine:

http://bl.ocks.org/mbostock/15a9eecf0b29db92f12ca823cfbbce0a

You should also be able to `import {event} from "d3"` if you use ES6 modules. But that gets tricky because you need to make sure that "d3" in that case refers to D3’s ES6 modules, and not the UMD bundle, so that the import is properly resolved.

**Comment by gnarf** [comment]
Okay, tested with `d3.event` in my fiddle... 

I am doing `import {event} from "d3";` but still having this problem in my production code.

**Comment by mbostock** [comment]
Right. The `import {event} from "d3"` is probably an issue with Babel not respecting that imports are [live bindings](http://www.2ality.com/2015/07/es6-module-exports.html), not values. But I’m not sure whether that problem is caused by Babel trying to import from the D3 UMD bundle or whether it’s observing the jsnext:main field in the package.json like Rollup does and pulling directly from the ES modules.

**Comment by gnarf** [comment]
So yeah -- I got this working now...

Had to in my webpack force it to resolve "d3" to `d3/index.js` instead of the `d3/build/d3.js`, and ensure babel was parsing the `node_modules/d3` directories

However this is a very annoying problem that I'm sure will catch a lot of users... Perhaps you should build a `safer` export for event. Even something as silly as `import {d3event} from 'd3'; d3event.event` might be a safe alias for UMD users that wont have binding/destructuring problems like I just did...

**Comment by mbostock** [comment]
Does webpack not observe jsnext:main? Is there some other magic I can put in the package.json to tell it to find index.js instead of build/d3.js?

**Comment by mbostock** [comment]
Appears not: webpack/webpack#1979.

**Comment by mbostock** [comment]
I’ve added some text to the README that will hopefully help avoid this issue:

> If you use Babel, Webpack, or another ES6-to-ES5 bundler, be aware that the value of d3.event changes during an event! An import of d3.event must be a [live binding](http://www.2ality.com/2015/07/es6-module-exports.html), so you may need to configure the bundler to import from D3’s ES6 modules rather than from the generated UMD bundle; not all bundlers observe [jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main). Also beware of conflicts with the [*window*.event](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) global.

https://github.com/d3/d3-selection/blob/master/README.md#event
